import Head from 'next/head'
import { GetServerSideProps } from 'next'
import {imageUrlBuilder, sanity, TextBlocks, textBlocksProjectionFragment} from 'src/lib/sanity'
import { Container } from 'src/lib/ui/layout/Container'
import { Row } from 'src/lib/ui/layout/Row'

export default function Page({ article }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h1>{article.title}</h1>
          <TextBlocks blocks={article.body} />
        </Container>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {

  const articles = await sanity.fetch(`
  *[_type == "article" && slug.current == $slug]{
    ...,
    'body': body[] ${textBlocksProjectionFragment}
  }`, { slug: context.params.slug });
  const article = articles[0];

  if (!article) { 
    return {
      notFound: true,
    }
  }

  return {
    props: {
      article
    }
  }
}