import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
//
import { GetServerSideProps } from "next";
import { imageUrlBuilder, sanity } from "src/lib/sanity";
import Link from "next/link";
import { Container } from "src/lib/ui/layout/Container";
import { Row } from "src/lib/ui/layout/Row";
import { css } from "@emotion/react";
import { AutoGrid } from "src/lib/ui/layout/AutoGrid";
import SideBar from "src/lib/SideBar";

export default function Page({ products }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Row breakAt="900px" columns="300px 1fr">
            <SideBar />
            <div>
              <h1
                css={css`
                  margin-top: 0;
                `}
              >
                The furniture store
              </h1>
              <h2>Products</h2>

              <AutoGrid>
                {products.map((product, i) => (
                  <div
                    key={i}
                    css={css`
                      margin-bottom: 50px;
                      margin-right: 30px;
                      margin-left: 30px;
                    `}
                  >
                    <Link
                      css={css`
                        text-decoration: none;
                      `}
                      href={`/products/${product.slug?.current}`}
                    >
                      <div
                        css={css`
                          background-color: #bcc6cc;
                        `}
                      >
                        <img
                          src={imageUrlBuilder
                            .image(product.productImage)
                            .width(256)
                            .height(256)
                            .url()}
                          alt="Product image"
                        />
                      </div>
                      <h3
                        css={css`
                          color: black;
                        `}
                      >
                        {product.productName}
                      </h3>
                      <h3
                        css={css`
                          color: #808080;
                        `}
                      >
                        (${product.price})
                      </h3>
                    </Link>
                  </div>
                ))}
              </AutoGrid>
            </div>
          </Row>
        </Container>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const products = await sanity.fetch(`*[_type == "product"]`, {});

  return {
    props: {
      products,
    },
  };
};
